spring.application.name=asistencia

# DataBase configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/asistencia
spring.datasource.username=postgres
spring.datasource.password=alan123


#JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Swagger Configuration

# server.servlet.context-path=/api
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.csrf.enabled=false

# Configuración para ver excepciones en el log
logging.level.com.example.BackendProject=DEBUG
logging.level.io.swagger=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG


#JWT
security.jwt.expiration-minutes=30
security.jwt.secret-key=ZXN0ZUVzVW5TZWNyZXRvU3VwZXJMYXJnb1lTZWd1cm8xMjM0
